-- ============================================
-- Flyway 数据库迁移脚本 V1.0
-- 描述: Delta AI Customer Service 初始化建表脚本
-- 作者: 刘建国
-- 日期: 2026-05-09
-- 数据库: delta_ai_customer_service
-- 表数量: 约42张业务表
-- ============================================

CREATE TABLE `activity_package` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint DEFAULT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `game_config_id` bigint DEFAULT NULL COMMENT '娓告垙閰嶇疆ID',
  `title` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '濂楅鏍囬',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '鎻忚堪',
  `activity_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娲诲姩绫诲瀷',
  `service_item_ids` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍖呭惈鐨勬湇鍔￠」鐩甀D鍒楄〃',
  `package_price` decimal(10,2) NOT NULL COMMENT '濂楅浠锋牸',
  `original_price` decimal(10,2) DEFAULT NULL COMMENT '鍘熶环',
  `start_time` datetime DEFAULT NULL COMMENT '娲诲姩寮€濮嬫椂闂?,
  `end_time` datetime DEFAULT NULL COMMENT '娲诲姩缁撴潫鏃堕棿',
  `banner_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '妯箙鍥剧墖URL',
  `terms` text COLLATE utf8mb4_unicode_ci COMMENT '鏉℃璇存槑',
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭搴忓彿',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_activity_package_club_config_id` (`club_config_id`) USING BTREE,
  KEY `idx_activity_package_enabled` (`enabled`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='娲诲姩濂楅琛?;
CREATE TABLE `ai_config` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `config_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '閰嶇疆閿悕',
  `config_value` text COLLATE utf8mb4_unicode_ci COMMENT '閰嶇疆鍊?,
  `config_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '閰嶇疆绫诲瀷锛岀敤浜庡垎缁勭鐞?,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '閰嶇疆鎻忚堪璇存槑',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI閰嶇疆琛?;
CREATE TABLE `ai_personality_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `club_config_id` bigint DEFAULT NULL,
  `personality_style` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `industry_style` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `game_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT '0',
  `emotion_intelligence_level` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT 'BASIC',
  `sentiment_sensitivity` int DEFAULT '5',
  `proactive_comfort` tinyint(1) DEFAULT '0',
  `address_format` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '?',
  `self_address` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '?',
  `emoji_usage` int DEFAULT '3',
  `slang_usage` int DEFAULT '2',
  `formality_level` int DEFAULT '4',
  `greeting_style` text COLLATE utf8mb4_unicode_ci,
  `max_reply_length` int DEFAULT '500',
  `use_game_terminology` tinyint(1) DEFAULT '0',
  `conversion_style` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT 'SOFT',
  `conversion_rate` double DEFAULT '0',
  `satisfaction_score` double DEFAULT '0',
  `total_conversations` bigint DEFAULT '0',
  `enabled` int DEFAULT '1',
  `priority` int DEFAULT '0',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` int NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_pc_club_config_id` (`club_config_id`) USING BTREE,
  KEY `idx_pc_game_type` (`game_type`) USING BTREE,
  KEY `idx_pc_personality_style` (`personality_style`) USING BTREE,
  KEY `idx_pc_enabled_priority` (`enabled`,`priority`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `campaign` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint DEFAULT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `campaign_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '娲诲姩鍚嶇О',
  `campaign_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '娲诲姩绫诲瀷锛歍RIAL-璇曠敤鎺ㄥ箍,REFERRAL-瑁傚彉鎷夋柊,HOLIDAY-鑺傛棩钀ラ攢,RECALL-澶嶈喘鍞ら啋,OTHER-鍏朵粬',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '娲诲姩鎻忚堪',
  `start_at` datetime DEFAULT NULL COMMENT '娲诲姩寮€濮嬫椂闂?,
  `end_at` datetime DEFAULT NULL COMMENT '娲诲姩缁撴潫鏃堕棿',
  `target_new_users` int DEFAULT '0' COMMENT '鐩爣鎷夋柊浜烘暟',
  `actual_new_users` int DEFAULT '0' COMMENT '瀹為檯鎷夋柊浜烘暟',
  `budget` decimal(10,2) DEFAULT '0.00' COMMENT '娲诲姩棰勭畻锛堝厓锛?,
  `actual_cost` decimal(10,2) DEFAULT '0.00' COMMENT '瀹為檯鑺辫垂锛堝厓锛?,
  `reward_rules` text COLLATE utf8mb4_unicode_ci COMMENT '濂栧姳鏂规鎻忚堪',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'DRAFT' COMMENT '娲诲姩鐘舵€侊細DRAFT-鑽夌,ACTIVE-杩涜涓?PAUSED-宸叉殏鍋?ENDED-宸茬粨鏉?CANCELLED-宸插彇娑?,
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_cam_club_config_id` (`club_config_id`),
  KEY `idx_cam_status` (`status`),
  KEY `idx_cam_start_at` (`start_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='钀ラ攢娲诲姩琛?;
CREATE TABLE `club_config` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '淇变箰閮ㄥ悕绉?,
  `club_logo` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '淇变箰閮↙ogo URL',
  `main_games` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '涓昏惀娓告垙锛屽涓父鎴忕敤閫楀彿鍒嗛殧',
  `service_slogan` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈嶅姟鍙ｅ彿/鏍囪',
  `welcome_message` text COLLATE utf8mb4_unicode_ci COMMENT '娆㈣繋璇紝鏂板鎴峰叧娉ㄦ椂鑷姩鍙戦€?,
  `contact_info` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鑱旂郴鏂瑰紡',
  `price_level_two` decimal(10,2) DEFAULT NULL COMMENT '浜屽搧闄帺甯堜环鏍硷紙鍏?灏忔椂锛?,
  `price_level_one` decimal(10,2) DEFAULT NULL COMMENT '涓€鍝侀櫔鐜╁笀浠锋牸锛堝厓/灏忔椂锛?,
  `price_top` decimal(10,2) DEFAULT NULL COMMENT '椤跺皷闄帺甯堜环鏍硷紙鍏?灏忔椂锛?,
  `price_star` decimal(10,2) DEFAULT NULL COMMENT '鏄庢槦闄帺甯堜环鏍硷紙鍏?灏忔椂锛?,
  `club_features` text COLLATE utf8mb4_unicode_ci COMMENT '淇变箰閮ㄧ壒鑹?,
  `custom_level_names` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鑷畾涔夌瓑绾у悕绉?,
  `service_promise` text COLLATE utf8mb4_unicode_ci COMMENT '鏈嶅姟鎵胯',
  `refund_policy` text COLLATE utf8mb4_unicode_ci COMMENT '閫€娆炬斂绛?,
  `member_discount` decimal(10,2) DEFAULT NULL COMMENT '浼氬憳鎶樻墸',
  `recharge_bonus` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍏呭€间紭鎯犺鏄?,
  `custom_welcome_template` text COLLATE utf8mb4_unicode_ci COMMENT '鑷畾涔夋杩庤妯℃澘',
  `ai_personality` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI浜烘牸閰嶇疆',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='淇变箰閮ㄩ厤缃〃';
CREATE TABLE `club_level_prices` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint NOT NULL COMMENT '鍏宠仈鐨勪勘涔愰儴閰嶇疆ID',
  `level_id` bigint NOT NULL COMMENT '鍏宠仈鐨勯櫔鐜╁笀绛夌骇ID',
  `price` decimal(10,2) NOT NULL COMMENT '璇ョ瓑绾у湪璇ヤ勘涔愰儴涓嬬殑浠锋牸锛堝厓/灏忔椂锛?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='淇变箰閮ㄧ瓑绾т环鏍煎叧鑱旇〃';
CREATE TABLE `club_subscription` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint NOT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `plan_id` bigint NOT NULL COMMENT '瀹氫环鏂规ID',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'TRIAL' COMMENT '璁㈤槄鐘舵€侊細TRIAL-璇曠敤涓?ACTIVE-鐢熸晥涓?EXPIRED-宸茶繃鏈?CANCELLED-宸插彇娑?,
  `start_at` datetime DEFAULT NULL COMMENT '璁㈤槄寮€濮嬫椂闂?,
  `expire_at` datetime DEFAULT NULL COMMENT '璁㈤槄鍒版湡鏃堕棿',
  `trial_end_at` datetime DEFAULT NULL COMMENT '璇曠敤鍒版湡鏃堕棿',
  `auto_renew` tinyint(1) DEFAULT '0' COMMENT '鏄惁鑷姩缁垂',
  `paid_amount` decimal(10,2) DEFAULT '0.00' COMMENT '瀹炰粯閲戦',
  `payment_method` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏀粯鏂瑰紡',
  `payment_transaction_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏀粯娴佹按鍙?,
  `paid_at` datetime DEFAULT NULL COMMENT '鏀粯鏃堕棿',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_cs_club_config_id` (`club_config_id`),
  KEY `idx_cs_status` (`status`),
  KEY `idx_cs_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='淇变箰閮ㄨ闃呰〃';
CREATE TABLE `companion_levels` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `level_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '绛夌骇鍚嶇О锛屽"浜屽搧"銆?涓€鍝?銆?椤跺皷"',
  `level_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '绛夌骇缂栫爜锛屽 LEVEL_TWO銆丩EVEL_ONE銆乀OP',
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭搴忓彿锛屾暟鍊艰秺灏忕瓑绾ц秺楂?,
  `base_price` decimal(10,2) DEFAULT NULL COMMENT '璇ョ瓑绾у熀纭€浠锋牸锛堝厓/灏忔椂锛?,
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '绛夌骇鎻忚堪',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_companion_levels_enabled` (`enabled`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闄帺甯堢瓑绾ц〃';
CREATE TABLE `companion_schedules` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `companion_id` bigint NOT NULL COMMENT '鍏宠仈鐨勯櫔鐜╁笀ID',
  `schedule_date` date NOT NULL COMMENT '鎺掔彮鏃ユ湡',
  `time_slot` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏃舵鏍囪瘑锛屽"涓婂崍"銆?涓嬪崍"銆?鏅氫笂"',
  `start_time` time DEFAULT NULL COMMENT '寮€濮嬫椂闂?,
  `end_time` time DEFAULT NULL COMMENT '缁撴潫鏃堕棿',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AVAILABLE' COMMENT '鐘舵€侊細AVAILABLE-鍙绾︼紝BOOKED-宸查绾︼紝UNAVAILABLE-涓嶅彲鐢?,
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞淇℃伅',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_companion_schedules_companion_id` (`companion_id`) USING BTREE,
  KEY `idx_companion_schedules_status` (`status`) USING BTREE,
  KEY `idx_companion_schedules_companion_start` (`companion_id`,`start_time`) USING BTREE,
  KEY `idx_schedules_companion_date` (`companion_id`,`schedule_date`),
  KEY `idx_schedules_date_status` (`schedule_date`,`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闄帺甯堟帓鐝〃';
CREATE TABLE `companion_settlement` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `companion_id` bigint NOT NULL COMMENT '闄帺甯圛D',
  `settlement_period` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '缁撶畻鍛ㄦ湡锛堝2026-05-01鑷?026-05-31锛?,
  `total_orders` int DEFAULT '0' COMMENT '鎺ュ崟鎬绘暟',
  `total_revenue` decimal(12,2) DEFAULT '0.00' COMMENT '璁㈠崟鎬绘敹鍏?,
  `platform_fee` decimal(12,2) DEFAULT '0.00' COMMENT '骞冲彴鍒嗘垚閲戦',
  `companion_income` decimal(12,2) DEFAULT '0.00' COMMENT '闄帺甯堝疄寰楅噾棰?,
  `deduction_amount` decimal(12,2) DEFAULT '0.00' COMMENT '鎵ｆ椤癸紙杩濊缃氭绛夛級',
  `deduction_reason` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎵ｆ鍘熷洜',
  `settlement_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING' COMMENT '缁撶畻鐘舵€侊細PENDING-寰呯粨绠?PROCESSING-缁撶畻涓?COMPLETED-宸茬粨绠?,
  `settled_at` datetime DEFAULT NULL COMMENT '瀹為檯缁撶畻鏃堕棿',
  `payment_method` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏀舵鏂瑰紡',
  `payment_account` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏀舵璐﹀彿',
  `confirm_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'UNCONFIRMED' COMMENT '闄帺甯堢‘璁ょ姸鎬侊細UNCONFIRMED-鏈‘璁?CONFIRMED-宸茬‘璁?DISPUTED-鏈夊紓璁?,
  `dispute_content` text COLLATE utf8mb4_unicode_ci COMMENT '鐢宠瘔鍐呭',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_cst_companion_id` (`companion_id`),
  KEY `idx_cst_status` (`settlement_status`),
  KEY `idx_cst_period` (`settlement_period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闄帺甯堢粨绠楄褰曡〃';
CREATE TABLE `companion_training` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `companion_id` bigint NOT NULL COMMENT '闄帺甯圛D',
  `course_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鍩硅璇剧▼鍚嶇О',
  `course_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鍩硅绫诲瀷锛歋ERVICE_STANDARD-鏈嶅姟瑙勮寖,SCRIPT_TEMPLATE-璇濇湳妯℃澘,COMPLIANCE-鍚堣鍩硅,GAME_SKILL-娓告垙鎶€鑳?,
  `course_content` text COLLATE utf8mb4_unicode_ci COMMENT '鍩硅鍐呭锛堟枃鏈?Markdown锛?,
  `training_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'NOT_STARTED' COMMENT '鍩硅鐘舵€侊細NOT_STARTED-鏈紑濮?IN_PROGRESS-杩涜涓?COMPLETED-宸插畬鎴?,
  `started_at` datetime DEFAULT NULL COMMENT '寮€濮嬪涔犳椂闂?,
  `completed_at` datetime DEFAULT NULL COMMENT '瀹屾垚瀛︿範鏃堕棿',
  `exam_score` int DEFAULT NULL COMMENT '鑰冩牳寰楀垎(0-100)',
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍩硅澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_ct_companion_id` (`companion_id`),
  KEY `idx_ct_status` (`training_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闄帺甯堝煿璁褰曡〃';
CREATE TABLE `companions` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `real_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鐪熷疄濮撳悕',
  `nickname` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏄电О',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎵嬫満鍙?,
  `wechat` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '寰俊鍙?,
  `level_id` bigint DEFAULT NULL COMMENT '绛夌骇ID',
  `avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶村儚URL',
  `game_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娓告垙绫诲瀷',
  `description` longtext COLLATE utf8mb4_unicode_ci COMMENT '涓汉绠€浠?,
  `price` decimal(10,2) DEFAULT NULL COMMENT '浠锋牸锛堝厓/灏忔椂锛?,
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `service_tags` longtext COLLATE utf8mb4_unicode_ci COMMENT '鏈嶅姟鏍囩',
  `supported_games` longtext COLLATE utf8mb4_unicode_ci COMMENT '鏀寔娓告垙鍒楄〃',
  `kd_ratio` decimal(5,2) DEFAULT NULL COMMENT 'K/D姣旂巼',
  `rank_level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娈典綅绛夌骇',
  `voice_sample_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '璇煶鏍锋湰URL',
  `rating_avg` decimal(3,2) DEFAULT NULL COMMENT '骞冲潎璇勫垎',
  `order_count` int DEFAULT '0' COMMENT '璁㈠崟鏁伴噺',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_companions_level_id` (`level_id`) USING BTREE,
  KEY `idx_companions_enabled` (`enabled`) USING BTREE,
  KEY `idx_companions_game_type` (`game_type`) USING BTREE,
  KEY `idx_companions_enabled_game_type` (`enabled`,`game_type`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闄帺甯堣〃';
CREATE TABLE `conversation_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `user_id` bigint NOT NULL COMMENT '鐢ㄦ埛ID',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '骞冲彴',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '鐘舵€?,
  `ai_model` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI妯″瀷',
  `message_count` int DEFAULT '0' COMMENT '娑堟伅鎬绘暟',
  `ai_message_count` int DEFAULT '0' COMMENT 'AI娑堟伅鏁?,
  `human_message_count` int DEFAULT '0' COMMENT '浜哄伐娑堟伅鏁?,
  `first_message_at` datetime DEFAULT NULL COMMENT '棣栨潯娑堟伅鏃堕棿',
  `last_message_at` datetime DEFAULT NULL COMMENT '鏈潯娑堟伅鏃堕棿',
  `resolved` int DEFAULT '0' COMMENT '鏄惁宸茶В鍐?,
  `context_summary` text COLLATE utf8mb4_unicode_ci COMMENT '涓婁笅鏂囨憳瑕?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='浼氳瘽琛?;
CREATE TABLE `cs_user_customer` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `cs_user_id` bigint NOT NULL COMMENT '瀹㈡湇鐢ㄦ埛ID',
  `user_id` bigint NOT NULL COMMENT '瀹㈡埛鐢ㄦ埛ID',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '骞冲彴',
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
  `assigned_at` datetime DEFAULT NULL COMMENT '鍒嗛厤鏃堕棿',
  `assign_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍒嗛厤绫诲瀷锛歁ANUAL-鎵嬪姩锛孲YSTEM-绯荤粺',
  `assigned_by` bigint DEFAULT NULL COMMENT '鍒嗛厤鎿嶄綔浜篒D',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '鍏宠仈鐘舵€侊細ACTIVE-娲昏穬锛孖NACTIVE-闈炴椿璺?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_cs_user_customer_cs` (`cs_user_id`,`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡湇-瀹㈡埛鍏宠仈琛?;
CREATE TABLE `customer_order_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `customer_id` bigint NOT NULL COMMENT '瀹㈡埛ID',
  `user_id` bigint DEFAULT NULL,
  `order_id` bigint DEFAULT NULL COMMENT '璁㈠崟ID',
  `companion_id` bigint DEFAULT NULL,
  `record_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '璁板綍绫诲瀷',
  `order_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_time` datetime DEFAULT NULL,
  `duration_hours` decimal(10,1) DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `game_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `companion_level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_slot` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rating` int DEFAULT NULL,
  `review_content` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT 'COMPLETED',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_item_id` bigint DEFAULT NULL,
  `game_config_id` bigint DEFAULT NULL,
  `activity_package_id` bigint DEFAULT NULL,
  `guarantee_result` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci COMMENT '鍐呭',
  `operator_id` bigint DEFAULT NULL COMMENT '鎿嶄綔浜篒D',
  `operator_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔浜哄悕绉?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛璁㈠崟璁板綍琛?;
CREATE TABLE `customer_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `user_id` bigint NOT NULL COMMENT '鐢ㄦ埛ID',
  `rfm_recency_score` int DEFAULT NULL COMMENT 'RFM鏈€杩戞秷璐瑰緱鍒?,
  `rfm_frequency_score` int DEFAULT NULL COMMENT 'RFM娑堣垂棰戠巼寰楀垎',
  `rfm_monetary_score` int DEFAULT NULL COMMENT 'RFM娑堣垂閲戦寰楀垎',
  `rfm_total_score` int DEFAULT NULL COMMENT 'RFM缁煎悎寰楀垎',
  `rfm_segment` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'RFM鍒嗙兢鏍囩锛欳HAMPION-鍐犲啗锛孡OYAL-蹇犲疄锛孭OTENTIAL-娼滃姏锛孨EW-鏂板锛孉T_RISK-椋庨櫓锛孒IBERNATE-浼戠湢锛孡OST-娴佸け',
  `total_orders` int DEFAULT '0' COMMENT '鎬昏鍗曟暟',
  `total_spent` decimal(12,2) DEFAULT '0.00' COMMENT '鎬绘秷璐归噾棰?,
  `spending_level` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'spending level (HIGH/MEDIUM/LOW)',
  `avg_order_amount` decimal(10,2) DEFAULT NULL COMMENT '骞冲潎璁㈠崟閲戦',
  `max_order_amount` decimal(10,2) DEFAULT NULL COMMENT '鏈€澶ц鍗曢噾棰?,
  `spending_trend` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娑堣垂瓒嬪娍锛欼NCREASING-澧為暱锛孲TABLE-绋冲畾锛孌ECREASING-涓嬮檷',
  `repurchase_rate` decimal(4,2) DEFAULT NULL COMMENT '澶嶈喘鐜?,
  `estimated_ltv` decimal(12,2) DEFAULT NULL COMMENT '棰勪及瀹㈡埛缁堣韩浠峰€?,
  `avg_service_duration` decimal(10,2) DEFAULT NULL COMMENT '骞冲潎鏈嶅姟鏃堕暱',
  `last_order_at` datetime DEFAULT NULL COMMENT '鏈€鍚庝笅鍗曟椂闂?,
  `favorite_companion_id` bigint DEFAULT NULL COMMENT '鏈€鍠滄鐨勯櫔鐜╁笀ID',
  `favorite_game_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈€鍠滄鐨勬父鎴忕被鍨?,
  `game_preferences` text COLLATE utf8mb4_unicode_ci COMMENT 'game preferences',
  `preferred_time_slot` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍋忓ソ鏃舵',
  `preferred_companion_level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍋忓ソ闄帺甯堢瓑绾?,
  `preferred_order_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍋忓ソ璁㈠崟绫诲瀷',
  `companion_diversity` int DEFAULT '0' COMMENT '闄帺甯堝鏍锋€?,
  `first_contact_at` datetime DEFAULT NULL COMMENT '棣栨鎺ヨЕ鏃堕棿',
  `last_active_at` datetime DEFAULT NULL COMMENT '鏈€鍚庢椿璺冩椂闂?,
  `active_days` int DEFAULT '0' COMMENT '娲昏穬澶╂暟',
  `total_messages` int DEFAULT '0' COMMENT '鎬绘秷鎭暟',
  `ai_interaction_count` int DEFAULT '0' COMMENT 'AI浜や簰娆℃暟',
  `manual_interaction_count` int DEFAULT '0' COMMENT '浜哄伐浜や簰娆℃暟',
  `ai_ratio` decimal(4,2) DEFAULT NULL COMMENT 'AI浜や簰鍗犳瘮',
  `human_handoff_count` int DEFAULT '0' COMMENT '杞汉宸ユ鏁?,
  `top_handoff_reason` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈€甯歌杞汉宸ュ師鍥?,
  `emotion_trigger_count` int DEFAULT '0' COMMENT '鎯呯华瑙﹀彂娆℃暟',
  `order_intent_count` int DEFAULT '0' COMMENT '涓嬪崟鎰忓悜娆℃暟',
  `satisfaction_score` decimal(3,2) DEFAULT NULL COMMENT '婊℃剰搴﹁瘎鍒?,
  `satisfaction_trend` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '婊℃剰搴﹁秼鍔?,
  `complaint_count` int DEFAULT '0' COMMENT '鎶曡瘔娆℃暟',
  `refund_count` int DEFAULT '0' COMMENT '閫€娆炬鏁?,
  `avg_rating` decimal(3,2) DEFAULT NULL COMMENT '骞冲潎璇勫垎',
  `lifecycle_stage` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鐢熷懡鍛ㄦ湡闃舵锛歂EW-鏂板锛孉CTIVE-娲昏穬锛孡OYAL-蹇犲疄锛孉T_RISK-娴佸け椋庨櫓锛孋HURNED-宸叉祦澶?,
  `member_level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'NORMAL' COMMENT '浼氬憳绛夌骇锛歂ORMAL-鏅€氾紝BRONZE-閾滅墝锛孲ILVER-閾剁墝锛孏OLD-閲戠墝锛孭LATINUM-鐧介噾锛孌IAMOND-閽荤煶',
  `risk_level` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '椋庨櫓绛夌骇锛歀OW-浣庯紝MEDIUM-涓紝HIGH-楂?,
  `churn_risk_score` decimal(5,2) DEFAULT NULL COMMENT '娴佸け椋庨櫓璇勫垎',
  `primary_need_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '涓昏闇€姹傜被鍨?,
  `need_tags` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '闇€姹傛爣绛?,
  `tags` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏍囩',
  `remark` text COLLATE utf8mb4_unicode_ci COMMENT '澶囨敞',
  `assigned_cs_user_id` bigint DEFAULT NULL COMMENT 'assigned cs user id',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_customer_profile_user_id` (`user_id`) USING BTREE,
  KEY `idx_customer_profile_stage_active` (`lifecycle_stage`,`last_active_at`),
  KEY `idx_customer_profile_rfm_risk` (`rfm_segment`,`risk_level`),
  KEY `idx_customer_profile_member_level` (`member_level`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛鐢诲儚琛?;
CREATE TABLE `customer_satisfaction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `user_id` bigint NOT NULL COMMENT '瀹㈡埛ID',
  `related_order_id` bigint DEFAULT NULL COMMENT '鍏宠仈鏈嶅姟杩借釜ID',
  `related_companion_id` bigint DEFAULT NULL COMMENT '闄帺甯圛D',
  `satisfaction_score` int DEFAULT NULL COMMENT '璇勫垎锛?-5锛?,
  `comment` text COLLATE utf8mb4_unicode_ci COMMENT '鍙嶉鍐呭',
  `feedback_tags` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏍囩锛堥€楀彿鍒嗛殧锛?,
  `is_anonymous` int DEFAULT '0' COMMENT '鏄惁鍖垮悕锛?-鍚︼紝1-鏄?,
  `service_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈嶅姟绫诲瀷',
  `reply_content` text COLLATE utf8mb4_unicode_ci COMMENT '鍥炲鍐呭',
  `replied_by` bigint DEFAULT NULL COMMENT '鍥炲浜篒D',
  `replied_at` datetime DEFAULT NULL COMMENT '鍥炲鏃堕棿',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛婊℃剰搴﹁〃';
CREATE TABLE `faq_items` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '闂鍒嗙被锛屽"鏈嶅姟娴佺▼"銆?浠锋牸璇存槑"',
  `question` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '闂鍐呭',
  `answer` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '绛旀鍐呭',
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭搴忓彿锛屾暟鍊艰秺灏忚秺闈犲墠',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_faq_items_category` (`category`) USING BTREE,
  KEY `idx_faq_items_enabled` (`enabled`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='FAQ鐭ヨ瘑搴撹〃';
CREATE TABLE `game_config` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint DEFAULT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `game_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '娓告垙鍚嶇О',
  `game_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娓告垙缂栫爜',
  `game_icon` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍥炬爣URL',
  `game_desc` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎻忚堪',
  `custom_settings` text COLLATE utf8mb4_unicode_ci COMMENT '鑷畾涔夎缃?,
  `game_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'FPS' COMMENT '娓告垙绫诲瀷',
  `base_hourly_price` decimal(10,2) DEFAULT NULL COMMENT '鍩虹鏃朵环',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭搴忓彿',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='娓告垙閰嶇疆琛?;
CREATE TABLE `game_knowledge` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `game_id` bigint DEFAULT NULL COMMENT '娓告垙ID',
  `category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍒嗙被',
  `title` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏍囬',
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '鍐呭',
  `source` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏉ユ簮',
  `tags` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏍囩',
  `keywords` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍏抽敭璇?,
  `reliability` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍙潬鎬ц瘎绾?,
  `version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鐗堟湰',
  `effective_from` datetime DEFAULT NULL COMMENT '鐢熸晥寮€濮嬫椂闂?,
  `effective_to` datetime DEFAULT NULL COMMENT '鐢熸晥缁撴潫鏃堕棿',
  `view_count` int DEFAULT '0' COMMENT '鏌ョ湅娆℃暟',
  `helpful_count` int DEFAULT '0' COMMENT '鏈夊府鍔╂鏁?,
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='娓告垙鐭ヨ瘑搴撹〃';
CREATE TABLE `keywords` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `keyword` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鍏抽敭璇嶅唴瀹?,
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍏抽敭璇嶅垎绫伙細TRANSFER-杞汉宸ワ紝COMPLAINT-鎶曡瘔锛孫RDER-涓嬪崟锛孍MERGENCY-绱ф€?,
  `match_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'EXACT' COMMENT '鍖归厤鏂瑰紡锛欵XACT-绮剧‘锛孎UZZY-妯＄硦锛孯EGEX-姝ｅ垯',
  `action_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瑙﹀彂鍔ㄤ綔锛歊EPLY-鑷姩鍥炲锛孴RANSFER-杞汉宸ワ紝TAG-鏍囪锛孍SCALATE-鍗囩骇',
  `reply_id` bigint DEFAULT NULL COMMENT '鍏宠仈鐨勮嚜鍔ㄥ洖澶岻D',
  `priority` int DEFAULT '0' COMMENT '浼樺厛绾э紝鏁板€艰秺澶т紭鍏堢骇瓒婇珮',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '鏄惁鍚敤',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞璇存槑',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鍏抽敭璇嶈Е鍙戣〃';
CREATE TABLE `messages` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `session_id` bigint DEFAULT NULL COMMENT '浼氳瘽ID',
  `user_id` bigint NOT NULL COMMENT '鐢ㄦ埛ID',
  `direction` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '娑堟伅鏂瑰悜锛歩n-鎺ユ敹锛堝鎴峰彂閫侊級锛宱ut-鍙戝嚭锛堢郴缁?瀹㈡湇鍙戦€侊級',
  `content` longtext COLLATE utf8mb4_unicode_ci COMMENT '娑堟伅鍐呭',
  `content_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'text' COMMENT '鍐呭绫诲瀷锛歵ext-鏂囨湰锛宨mage-鍥剧墖绛?,
  `is_ai` tinyint(1) DEFAULT '0' COMMENT '鏄惁AI鍥炲',
  `ai_model` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AI妯″瀷鍚嶇О',
  `ai_token_count` int DEFAULT NULL COMMENT 'AI娑堣€桾oken鏁?,
  `ai_response_time_ms` int DEFAULT NULL COMMENT 'AI鍝嶅簲鏃堕棿锛堟绉掞級',
  `keyword_triggered` tinyint(1) DEFAULT '0' COMMENT '鏄惁瑙﹀彂鍏抽敭璇?,
  `triggered_keyword` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瑙﹀彂鐨勫叧閿瘝',
  `cs_user_id` bigint DEFAULT NULL COMMENT '瀹㈡湇鐢ㄦ埛ID',
  `emotion_tag` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎯呯华鏍囩',
  `intent_tag` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎰忓浘鏍囩',
  `read_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'unread' COMMENT '闃呰鐘舵€?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`,`created_at`),
  KEY `idx_messages_created_at` (`created_at`),
  KEY `idx_messages_user_id_created` (`user_id`,`created_at` DESC)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='娑堟伅琛?
/*!50100 PARTITION BY RANGE (to_days(`created_at`))
(PARTITION p202510 VALUES LESS THAN (739921) ENGINE = InnoDB,
 PARTITION p202511 VALUES LESS THAN (739951) ENGINE = InnoDB,
 PARTITION p202512 VALUES LESS THAN (739982) ENGINE = InnoDB,
 PARTITION p202601 VALUES LESS THAN (740013) ENGINE = InnoDB,
 PARTITION p202602 VALUES LESS THAN (740041) ENGINE = InnoDB,
 PARTITION p202603 VALUES LESS THAN (740072) ENGINE = InnoDB,
 PARTITION p202604 VALUES LESS THAN (740102) ENGINE = InnoDB,
 PARTITION p202605 VALUES LESS THAN (740133) ENGINE = InnoDB,
 PARTITION p202606 VALUES LESS THAN (740163) ENGINE = InnoDB,
 PARTITION p202607 VALUES LESS THAN (740194) ENGINE = InnoDB,
 PARTITION p_future VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */;
CREATE TABLE `messages_archive` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'message_id',
  `session_id` bigint DEFAULT NULL COMMENT 'session_id',
  `user_id` bigint DEFAULT NULL COMMENT 'user_id',
  `direction` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'direction',
  `content` longtext COLLATE utf8mb4_unicode_ci COMMENT 'content',
  `content_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'content_type',
  `is_ai` tinyint(1) DEFAULT NULL COMMENT 'is_ai',
  `ai_model` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ai_model',
  `ai_token_count` int DEFAULT NULL COMMENT 'token_count',
  `ai_response_time_ms` int DEFAULT NULL COMMENT 'response_time',
  `keyword_triggered` tinyint(1) DEFAULT NULL COMMENT 'keyword_triggered',
  `triggered_keyword` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'triggered_keyword',
  `cs_user_id` bigint DEFAULT NULL COMMENT 'cs_user_id',
  `emotion_tag` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'emotion_tag',
  `intent_tag` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'intent_tag',
  `read_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'read_status',
  `archived_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'archived_at',
  `created_at` datetime NOT NULL COMMENT 'created_at',
  `updated_at` datetime DEFAULT NULL COMMENT 'updated_at',
  PRIMARY KEY (`id`,`archived_at`),
  KEY `idx_archive_user_id` (`user_id`),
  KEY `idx_archive_session_id` (`session_id`),
  KEY `idx_archive_created_at` (`created_at`),
  KEY `idx_archive_archived_at` (`archived_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='messages_archive';
CREATE TABLE `operation_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `operation_time` datetime DEFAULT NULL COMMENT '鎿嶄綔鏃堕棿',
  `operator` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔浜?,
  `operation_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔绫诲瀷',
  `operation_target` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔鐩爣',
  `operation_content` text COLLATE utf8mb4_unicode_ci COMMENT '鎿嶄綔鍐呭',
  `operation_result` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔缁撴灉',
  `affected_rows` int DEFAULT NULL COMMENT '褰卞搷琛屾暟',
  `duration_ms` int DEFAULT NULL COMMENT '鑰楁椂锛堟绉掞級',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT '閿欒淇℃伅',
  `rollback_info` text COLLATE utf8mb4_unicode_ci COMMENT '鍥炴粴淇℃伅',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鎿嶄綔鏃ュ織琛?;
CREATE TABLE `orders` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `order_no` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '璁㈠崟缂栧彿',
  `user_id` bigint NOT NULL COMMENT '涓嬪崟瀹㈡埛ID',
  `companion_id` bigint DEFAULT NULL COMMENT '闄帺甯圛D',
  `companion_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '闄帺甯堝悕绉?,
  `service_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈嶅姟绫诲瀷',
  `price_rule_id` bigint DEFAULT NULL COMMENT '浠锋牸瑙勫垯ID',
  `order_status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '璁㈠崟鐘舵€侊細PENDING-寰呯‘璁わ紝CONFIRMED-宸茬‘璁わ紝IN_PROGRESS-杩涜涓紝COMPLETED-宸插畬鎴愶紝PENDING_REVIEW-寰呰瘎浠凤紝CANCELLED-宸插彇娑堬紝REFUNDED-宸查€€娆撅紝ABNORMAL-寮傚父锛孉RCHIVED-宸插綊妗?,
  `scheduled_start` datetime DEFAULT NULL COMMENT '棰勭害寮€濮嬫椂闂?,
  `scheduled_end` datetime DEFAULT NULL COMMENT '棰勭害缁撴潫鏃堕棿',
  `actual_start` datetime DEFAULT NULL COMMENT '瀹為檯寮€濮嬫椂闂?,
  `actual_end` datetime DEFAULT NULL COMMENT '瀹為檯缁撴潫鏃堕棿',
  `duration_minutes` int DEFAULT NULL COMMENT '鏈嶅姟鏃堕暱锛堝垎閽燂級',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '璁㈠崟鎬婚噾棰?,
  `paid_amount` decimal(10,2) DEFAULT NULL COMMENT '瀹炰粯閲戦',
  `payment_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'UNPAID' COMMENT '鏀粯鐘舵€侊細UNPAID-鏈敮浠橈紝PARTIAL-閮ㄥ垎鏀粯锛孭AID-宸叉敮浠?,
  `payment_method` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏀粯鏂瑰紡',
  `transaction_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '???????????????????????',
  `payment_time` datetime DEFAULT NULL COMMENT '?????????',
  `work_order_id` bigint DEFAULT NULL COMMENT '鍏宠仈宸ュ崟ID',
  `remark` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_orders_user_id` (`user_id`) USING BTREE,
  KEY `idx_orders_companion_id` (`companion_id`) USING BTREE,
  KEY `idx_orders_order_status` (`order_status`) USING BTREE,
  KEY `idx_orders_created_at` (`created_at`) USING BTREE,
  KEY `idx_orders_status_created` (`order_status`,`created_at`) USING BTREE,
  KEY `idx_orders_transaction_id` (`transaction_id`),
  KEY `idx_orders_status_payment_created` (`order_status`,`payment_status`,`created_at`),
  KEY `idx_orders_user_id_created` (`user_id`,`created_at` DESC),
  KEY `idx_orders_companion_status` (`companion_id`,`order_status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='璁㈠崟琛?;
CREATE TABLE `pending_messages` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `user_id` bigint NOT NULL COMMENT '瀹㈡埛ID',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '骞冲彴',
  `content` longtext COLLATE utf8mb4_unicode_ci COMMENT '娑堟伅鍐呭',
  `content_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'text' COMMENT '鍐呭绫诲瀷',
  `pending_reason` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '寰呭鐞嗗師鍥?,
  `priority` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'NORMAL' COMMENT '浼樺厛绾э細NORMAL-鏅€氾紝URGENT-绱ф€ワ紝CRITICAL-鐗规€?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  `status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `deadline` datetime DEFAULT NULL,
  `escalation_level` int DEFAULT '0',
  `assigned_cs_user_id` bigint DEFAULT NULL,
  `reminder_count` int DEFAULT '0',
  `keyword` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瑙﹀彂鍏抽敭璇?,
  `handled_by` bigint DEFAULT NULL COMMENT '澶勭悊浜虹敤鎴稩D',
  `handled_at` datetime DEFAULT NULL COMMENT '澶勭悊鏃堕棿',
  `remark` text COLLATE utf8mb4_unicode_ci COMMENT '澶勭悊澶囨敞',
  `context_summary` text COLLATE utf8mb4_unicode_ci COMMENT '涓婁笅鏂囨憳瑕?,
  `auto_reply_keyword` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '???閿熸枻鎷烽敓鏂ゆ嫹閿熸枻鎷疯尭閿熸枻鎷烽敓鏂ゆ嫹閿熸枻鎷?,
  `matched_intent` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'matched intent',
  `intent_confidence` decimal(5,2) DEFAULT NULL COMMENT 'intent confidence',
  `auto_reply_template` text COLLATE utf8mb4_unicode_ci COMMENT 'auto reply template',
  `auto_reply_at` datetime DEFAULT NULL COMMENT 'auto reply time',
  `auto_reply_used` tinyint DEFAULT '0' COMMENT 'auto reply used',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_pm_status` (`status`),
  KEY `idx_pm_status_deadline` (`status`,`deadline`),
  KEY `idx_pm_status_deleted_deadline` (`status`,`deleted`,`deadline`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='寰呭鐞嗘秷鎭〃';
CREATE TABLE `platform_configs` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '骞冲彴鏍囪瘑锛歸echat-寰俊锛寃ework-浼佸井锛宬ook-KOOK锛寉y-YY',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '鏄惁鍚敤璇ュ钩鍙版帴鍏?,
  `config` json DEFAULT NULL COMMENT '骞冲彴鐗瑰畾閰嶇疆锛孞SON鏍煎紡瀛樺偍',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='骞冲彴閰嶇疆琛?;
CREATE TABLE `pricing_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `plan_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏂规缂栫爜锛欱ASIC/PRO/ENTERPRISE',
  `plan_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏂规鍚嶇О锛氬熀纭€鐗?涓撲笟鐗?浼佷笟鐗?,
  `monthly_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '鏈堣垂浠锋牸',
  `yearly_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '骞磋垂浠锋牸锛堣喘涔板勾璐逛韩鎶樻墸锛?,
  `per_call_price` decimal(10,4) DEFAULT '0.0000' COMMENT '鎸夋浠樿垂鍗曚环锛堝厓/娆I瀵硅瘽锛?,
  `daily_price` decimal(10,2) DEFAULT '0.00' COMMENT '鏃ヤ細鍛樹环鏍硷紙9.9鍏?鏃ワ級',
  `max_companions` int DEFAULT '5' COMMENT '闄帺甯堟暟閲忎笂闄?,
  `max_monthly_messages` int DEFAULT '0' COMMENT '鏈堟秷鎭噺涓婇檺锛?=鏃犻檺鍒讹級',
  `max_personality_templates` int DEFAULT '2' COMMENT 'AI浜烘牸妯℃澘鏁伴噺涓婇檺',
  `emotion_intelligence_level` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'BASIC' COMMENT '鎯呯华鏅鸿兘绛夌骇锛欱ASIC/ADVANCED/PREMIUM',
  `include_smart_dispatch` tinyint(1) DEFAULT '0' COMMENT '鏄惁鍖呭惈鏅鸿兘娲惧崟',
  `include_full_quality_check` tinyint(1) DEFAULT '0' COMMENT '鏄惁鍖呭惈鍏ㄦ祦绋嬭川妫€',
  `include_analytics` tinyint(1) DEFAULT '0' COMMENT '鏄惁鍖呭惈鏁版嵁鍒嗘瀽',
  `include_brand_custom` tinyint(1) DEFAULT '0' COMMENT '鏄惁鏀寔鑷畾涔夊搧鐗?,
  `include_api_access` tinyint(1) DEFAULT '0' COMMENT '鏄惁鏀寔API鎺ュ叆',
  `features` text COLLATE utf8mb4_unicode_ci COMMENT '鍔熻兘鎻忚堪锛圡arkdown鏍煎紡锛?,
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭鍙?,
  `status` tinyint DEFAULT '1' COMMENT '鐘舵€侊細1-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_pp_plan_code` (`plan_code`),
  KEY `idx_pp_status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹氫环鏂规琛?;
CREATE TABLE `quality_check_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `order_id` bigint DEFAULT NULL COMMENT '鍏宠仈璁㈠崟ID',
  `companion_id` bigint DEFAULT NULL COMMENT '鍏宠仈闄帺甯圛D',
  `user_id` bigint DEFAULT NULL COMMENT '鍏宠仈瀹㈡埛ID',
  `check_time` datetime NOT NULL COMMENT '妫€娴嬫椂闂?,
  `check_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '妫€娴嬬被鍨嬶細SERVICE-鏈嶅姟璐ㄩ噺,CONTENT-鍐呭鍚堣,ATTITUDE-鏈嶅姟鎬佸害,SPEED-鍝嶅簲閫熷害',
  `risk_level` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SAFE' COMMENT '椋庨櫓绛夌骇锛歋AFE-瀹夊叏,LOW-浣庨闄?MEDIUM-涓闄?HIGH-楂橀闄?CRITICAL-涓ラ噸杩濊',
  `score` int DEFAULT '0' COMMENT '妫€娴嬪緱鍒?1-100)',
  `violation_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '杩濊绫诲瀷锛歋EXUAL-娑夐粍,GAMBLING-娑夎祵,CHEAT-澶栨寕,ABUSE-杈遍獋,REPLACE-浠ｆ墦,OTHER-鍏朵粬',
  `violation_summary` text COLLATE utf8mb4_unicode_ci COMMENT '杩濊鍐呭鎽樿',
  `evidence_url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '璇佹嵁鎴浘/褰曢煶URL',
  `action_suggestion` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶勭悊寤鸿',
  `handle_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING' COMMENT '澶勭悊鐘舵€侊細PENDING-寰呭鐞?REVIEWED-宸插鏍?RESOLVED-宸插鐞?IGNORED-宸插拷鐣?,
  `handler_id` bigint DEFAULT NULL COMMENT '澶勭悊浜篒D',
  `handle_remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶勭悊澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_qcr_order_id` (`order_id`),
  KEY `idx_qcr_companion_id` (`companion_id`),
  KEY `idx_qcr_check_time` (`check_time`),
  KEY `idx_qcr_risk_level` (`risk_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鏈嶅姟璐ㄩ噺妫€娴嬭褰曡〃';
CREATE TABLE `referral_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `campaign_id` bigint DEFAULT NULL COMMENT '鍏宠仈钀ラ攢娲诲姩ID',
  `referrer_user_id` bigint NOT NULL COMMENT '鎺ㄨ崘浜虹敤鎴稩D锛堣€佸鎴凤級',
  `referee_user_id` bigint DEFAULT NULL COMMENT '琚帹鑽愪汉鐢ㄦ埛ID锛堟柊瀹㈡埛锛?,
  `referral_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎺ㄨ崘鐮?,
  `referral_time` datetime NOT NULL COMMENT '鎺ㄨ崘鏃堕棿',
  `conversion_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING' COMMENT '杞寲鐘舵€侊細PENDING-寰呮敞鍐?REGISTERED-宸叉敞鍐?TRIALING-璇曠敤涓?SUBSCRIBED-宸蹭粯璐?,
  `converted_at` datetime DEFAULT NULL COMMENT '杞寲鏃堕棿锛堟敞鍐?浠樿垂鏃堕棿锛?,
  `reward_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎺ㄨ崘浜哄鍔辩被鍨嬶細MONTH_FREE-璧犻€佹湀浼氬憳,CASH-鐜伴噾濂栧姳,POINTS-绉垎濂栧姳',
  `reward_amount` decimal(10,2) DEFAULT '0.00' COMMENT '鎺ㄨ崘浜哄鍔遍噾棰濓紙鍏冿級',
  `reward_status` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'PENDING' COMMENT '濂栧姳鍙戞斁鐘舵€侊細PENDING-寰呭彂鏀?ISSUED-宸插彂鏀?CANCELLED-宸插彇娑?,
  `reward_issued_at` datetime DEFAULT NULL COMMENT '濂栧姳鍙戞斁鏃堕棿',
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶囨敞',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_rr_referrer_id` (`referrer_user_id`),
  KEY `idx_rr_referee_id` (`referee_user_id`),
  KEY `idx_rr_status` (`conversion_status`),
  KEY `idx_rr_campaign_id` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瑁傚彉鎺ㄨ崘璁板綍琛?;
CREATE TABLE `replies` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `trigger_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '瑙﹀彂绫诲瀷锛歬eyword-鍏抽敭璇嶈Е鍙戯紝welcome-鏂扮敤鎴峰叧娉ㄨЕ鍙戯紝default-榛樿鍥炲',
  `trigger_key` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '瑙﹀彂閿紝鍏抽敭璇嶈Е鍙戞椂涓哄叿浣撳叧閿瘝锛屾杩庤Е鍙戞椂涓?welcome"',
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鍥炲鍐呭',
  `enabled` tinyint(1) DEFAULT '1' COMMENT '鏄惁鍚敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_replies_enabled` (`enabled`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鑷姩鍥炲瑙勫垯琛?;
CREATE TABLE `revenue_daily_report` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint NOT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `report_date` date NOT NULL COMMENT '鎶ヨ〃鏃ユ湡',
  `game_type` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '娓告垙绫诲瀷锛坣ull=鍏ㄦ父鎴忓悎璁★級',
  `total_orders` int DEFAULT '0' COMMENT '璁㈠崟鎬绘暟',
  `completed_orders` int DEFAULT '0' COMMENT '宸插畬鎴愯鍗曟暟',
  `refund_orders` int DEFAULT '0' COMMENT '閫€娆捐鍗曟暟',
  `total_revenue` decimal(14,2) DEFAULT '0.00' COMMENT '璁㈠崟鎬绘敹鍏?,
  `platform_income` decimal(14,2) DEFAULT '0.00' COMMENT '骞冲彴鍒嗘垚鏀跺叆',
  `ai_conversations` int DEFAULT '0' COMMENT 'AI浼氳瘽鎬绘暟',
  `ai_handle_rate` decimal(5,2) DEFAULT '0.00' COMMENT 'AI澶勭悊鐜?%)',
  `avg_satisfaction` decimal(3,2) DEFAULT '0.00' COMMENT '瀹㈡埛婊℃剰搴﹀潎鍒?,
  `new_customers` int DEFAULT '0' COMMENT '鏂板鎴锋暟',
  `repeat_customers` int DEFAULT '0' COMMENT '鑰佸鎴峰璐暟',
  `active_companions` int DEFAULT '0' COMMENT '娲昏穬闄帺甯堟暟',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` tinyint DEFAULT '0' COMMENT '閫昏緫鍒犻櫎鏍囪',
  `deleted_at` datetime DEFAULT NULL COMMENT '閫昏緫鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`),
  KEY `idx_rdr_club_config_id` (`club_config_id`),
  KEY `idx_rdr_report_date` (`report_date`),
  KEY `idx_rdr_game_type` (`game_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='钀ユ敹鏃ユ姤琛?;
CREATE TABLE `service_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `club_config_id` bigint DEFAULT NULL COMMENT '淇变箰閮ㄩ厤缃甀D',
  `game_config_id` bigint DEFAULT NULL COMMENT '娓告垙閰嶇疆ID',
  `service_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '椤圭洰鍚嶇О',
  `service_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '椤圭洰缂栫爜',
  `service_desc` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎻忚堪',
  `service_icon` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍥炬爣',
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍒嗙被锛欰CCOMPANY-闄帺锛孭ACKAGE-濂楅锛孴EACHING-鏁欏锛孲OCIAL-绀句氦',
  `base_price` decimal(10,2) DEFAULT NULL COMMENT '鍩虹浠锋牸',
  `price_unit` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'HOUR' COMMENT '浠锋牸鍗曚綅锛欻OUR-灏忔椂锛孨IGHT-鍖呭锛孫RDER-鎸夊崟',
  `min_duration` decimal(10,2) DEFAULT NULL COMMENT '鏈€鐭椂闀?,
  `guarantee_text` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '淇濋殰璇存槑',
  `refund_policy` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '閫€娆炬斂绛?,
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `sort_order` int DEFAULT '0' COMMENT '鎺掑簭搴忓彿',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鏈嶅姟椤圭洰琛?;
CREATE TABLE `service_price_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `service_item_id` bigint NOT NULL COMMENT '鏈嶅姟椤圭洰ID',
  `companion_level_id` bigint NOT NULL COMMENT '闄帺甯堢瓑绾D',
  `price` decimal(10,2) NOT NULL COMMENT '浠锋牸',
  `original_price` decimal(10,2) DEFAULT NULL COMMENT '鍘熶环',
  `price_unit` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'HOUR' COMMENT '浠锋牸鍗曚綅',
  `enabled` int NOT NULL DEFAULT '1' COMMENT '鏄惁鍚敤锛?-鍚敤锛?-绂佺敤',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_spr_service_item_id` (`service_item_id`) USING BTREE,
  KEY `idx_spr_companion_level_id` (`companion_level_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鏈嶅姟浠锋牸瑙勫垯琛?;
CREATE TABLE `service_tracks` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `user_id` bigint NOT NULL COMMENT '瀹㈡埛ID',
  `track_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '杩借釜绫诲瀷',
  `related_id` bigint DEFAULT NULL COMMENT '鍏宠仈ID',
  `track_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鐘舵€侊細CONSULTING-鍜ㄨ涓紝BOOKED-宸查绾︼紝SERVICING-鏈嶅姟涓紝SERVICE_DONE-鏈嶅姟瀹屾垚锛孋ONFIRMED-宸茬‘璁?,
  `current_step` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '褰撳墠姝ラ',
  `track_data` varchar(4000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '杩借釜鏁版嵁锛圝SON鏍煎紡锛?,
  `started_at` datetime DEFAULT NULL COMMENT '寮€濮嬫椂闂?,
  `completed_at` datetime DEFAULT NULL COMMENT '瀹屾垚鏃堕棿',
  `duration_seconds` int DEFAULT NULL COMMENT '鎸佺画鏃堕暱锛堢锛?,
  `result` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缁撴灉',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='鏈嶅姟杩借釜琛?;
CREATE TABLE `sys_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '??',
  `perm_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '????',
  `perm_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '????',
  `perm_group` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '????',
  `action_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '????',
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '????',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `status` tinyint DEFAULT '1' COMMENT '???1-???0-??',
  PRIMARY KEY (`id`),
  KEY `idx_sp_code` (`perm_code`),
  KEY `idx_sp_group` (`perm_group`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='?????';
CREATE TABLE `sys_role` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '??',
  `role_code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '????',
  `role_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '????',
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '????',
  `is_system` tinyint DEFAULT '0' COMMENT '?????????1-??0-?',
  `status` tinyint DEFAULT '1' COMMENT '???1-???0-??',
  `sort_order` int DEFAULT '0' COMMENT '???',
  `created_by` bigint DEFAULT NULL COMMENT '???',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '????',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '????',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '?????0-???1-??',
  `deleted_at` datetime DEFAULT NULL COMMENT '????',
  PRIMARY KEY (`id`),
  KEY `idx_sr_code` (`role_code`),
  KEY `idx_sr_status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='?????';
CREATE TABLE `sys_role_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '??',
  `role_id` bigint NOT NULL COMMENT '??ID',
  `perm_id` bigint NOT NULL COMMENT '??ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_perm` (`role_id`,`perm_id`),
  KEY `idx_srp_role_id` (`role_id`),
  KEY `idx_srp_perm_id` (`perm_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='??-?????';
CREATE TABLE `sys_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鐢ㄦ埛鍚?,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '瀵嗙爜锛圔Crypt鍔犲瘑锛?,
  `real_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鐪熷疄濮撳悕',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎵嬫満鍙?,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '閭',
  `role` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CS_STAFF' COMMENT '瑙掕壊锛歋YS_ADMIN-绯荤粺绠＄悊鍛橈紝CS_LEADER-瀹㈡湇璐熻矗浜猴紝CS_STAFF-鏅€氬鏈?,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT '鐘舵€侊細PENDING-寰呭鏍革紝ACTIVE-姝ｅ父锛孌ISABLED-绂佺敤',
  `created_by` bigint DEFAULT NULL COMMENT '鍒涘缓浜篒D',
  `two_factor_enabled` tinyint(1) DEFAULT '0' COMMENT '??????????????0-????? 1-?????',
  `two_factor_secret` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '???????????Base32???)',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_sys_user_role` (`role`) USING BTREE,
  KEY `idx_sys_user_status` (`status`) USING BTREE,
  KEY `idx_sys_user_role_status` (`role`,`status`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='绯荤粺鐢ㄦ埛琛?;
CREATE TABLE `sys_user_role` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '??',
  `user_id` bigint NOT NULL COMMENT '??ID',
  `role_id` bigint NOT NULL COMMENT '??ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
  KEY `idx_sur_user_id` (`user_id`),
  KEY `idx_sur_role_id` (`role_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='??-?????';
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏉ユ簮骞冲彴锛歸echat銆乼est绛?,
  `platform_user_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '骞冲彴渚х敤鎴稩D锛屽寰俊鐨刼penid',
  `nickname` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瀹㈡埛鏄电О',
  `avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶村儚URL',
  `ai_enabled` tinyint(1) DEFAULT '1' COMMENT '鏄惁鍚敤AI鑷姩鍥炲锛?-AI鍥炲锛?-浠呬汉宸?,
  `assigned_cs_user_id` bigint DEFAULT NULL COMMENT '鍒嗛厤鐨勪笓灞炲鏈岻D锛坰ys_user琛級锛孨ULL琛ㄧず鏈垎閰?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_users_platform` (`platform`) USING BTREE,
  KEY `idx_users_created_at` (`created_at`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛鐢ㄦ埛琛?;
CREATE TABLE `work_order_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `work_order_id` bigint NOT NULL COMMENT '鍏宠仈宸ュ崟ID',
  `record_id` bigint DEFAULT NULL COMMENT '鍏宠仈璁板綍ID',
  `file_name` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏂囦欢鍚?,
  `file_path` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '鏂囦欢璺緞',
  `file_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏂囦欢绫诲瀷锛欼MAGE-鍥剧墖锛孷IDEO-瑙嗛锛孌OCUMENT-鏂囨。锛孉UDIO-闊抽',
  `file_size` bigint DEFAULT NULL COMMENT '鏂囦欢澶у皬锛堝瓧鑺傦級',
  `uploaded_by` bigint DEFAULT NULL COMMENT '涓婁紶浜篒D',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_work_order_attachments_work_order_id` (`work_order_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宸ュ崟闄勪欢琛?;
CREATE TABLE `work_order_records` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `work_order_id` bigint NOT NULL COMMENT '宸ュ崟ID',
  `record_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '璁板綍绫诲瀷锛歋TATUS_CHANGE-鐘舵€佸彉鏇达紝HANDLE_RECORD-澶勭悊璁板綍锛孖NTERNAL_NOTE-鍐呴儴澶囨敞锛孲YSTEM_LOG-绯荤粺鏃ュ織',
  `operator_id` bigint DEFAULT NULL COMMENT '鎿嶄綔浜篒D',
  `operator_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔浜哄悕绉?,
  `operator_role` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鎿嶄綔浜鸿鑹?,
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '鍐呭',
  `old_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏃х姸鎬?,
  `new_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏂扮姸鎬?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_wor_work_order_id` (`work_order_id`) USING BTREE,
  KEY `idx_wor_operator_id` (`operator_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宸ュ崟璁板綍琛?;
CREATE TABLE `work_orders` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '涓婚敭ID',
  `order_no` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '宸ュ崟缂栧彿',
  `source_id` bigint DEFAULT NULL COMMENT '鏉ユ簮ID',
  `order_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '宸ュ崟绫诲瀷锛欳ONSULT-鍜ㄨ锛孊OOKING-棰勭害锛孋OMPLAINT-鎶曡瘔锛孯EFUND-閫€娆撅紝SERVICE_TRACK-鏈嶅姟杩借釜锛孫THER-鍏朵粬',
  `priority` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'NORMAL' COMMENT '浼樺厛绾э細NORMAL-鏅€氾紝URGENT-绱ф€ワ紝CRITICAL-鐗规€?,
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '骞冲彴',
  `user_id` bigint DEFAULT NULL COMMENT '瀹㈡埛ID',
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瀹㈡埛濮撳悕',
  `customer_contact` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瀹㈡埛鑱旂郴鏂瑰紡',
  `customer_level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瀹㈡埛绛夌骇',
  `service_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈嶅姟绫诲瀷',
  `service_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鏈嶅姟鐘舵€侊細PRE_SERVICE-鏈嶅姟鍓嶏紝IN_SERVICE-鏈嶅姟涓紝POST_SERVICE-鏈嶅姟鍚?,
  `problem_detail` longtext COLLATE utf8mb4_unicode_ci COMMENT '闂鎻忚堪',
  `problem_category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '闂鍒嗙被',
  `trigger_keyword` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '瑙﹀彂鍏抽敭璇?,
  `context_summary` longtext COLLATE utf8mb4_unicode_ci COMMENT '涓婁笅鏂囨憳瑕?,
  `assigned_cs_user_id` bigint DEFAULT NULL COMMENT '鍒嗛厤鐨勫鏈岻D',
  `assigned_cs_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '鍒嗛厤鐨勫鏈嶅悕绉?,
  `handler_id` bigint DEFAULT NULL COMMENT '澶勭悊浜篒D',
  `handler_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '澶勭悊浜哄悕绉?,
  `handle_result` text COLLATE utf8mb4_unicode_ci COMMENT '澶勭悊缁撴灉',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'NEW' COMMENT '宸ュ崟鐘舵€侊細NEW-鏂板缓锛孭ROCESSING-澶勭悊涓紝PENDING_CONFIRM-寰呯‘璁わ紝COMPLETED-宸插畬鎴愶紝CLOSED-宸插叧闂紝CANCELLED-宸插彇娑?,
  `deadline` datetime DEFAULT NULL COMMENT '鎴鏃堕棿',
  `escalation_level` int DEFAULT '0' COMMENT '鍗囩骇绾у埆',
  `reminder_count` int DEFAULT '0' COMMENT '鎻愰啋娆℃暟',
  `resolved_at` datetime DEFAULT NULL COMMENT '瑙ｅ喅鏃堕棿',
  `closed_at` datetime DEFAULT NULL COMMENT '鍏抽棴鏃堕棿',
  `related_order_id` bigint DEFAULT NULL COMMENT '鍏宠仈璁㈠崟ID',
  `related_companion_id` bigint DEFAULT NULL COMMENT '鍏宠仈闄帺甯圛D',
  `satisfaction_score` int DEFAULT NULL COMMENT '婊℃剰搴﹁瘎鍒?,
  `satisfaction_remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '婊℃剰搴﹀娉?,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
  `deleted` int NOT NULL DEFAULT '0' COMMENT '閫昏緫鍒犻櫎锛?-鏈垹闄わ紝1-宸插垹闄?,
  `deleted_at` datetime DEFAULT NULL COMMENT '鍒犻櫎鏃堕棿',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_work_orders_user_id` (`user_id`) USING BTREE,
  KEY `idx_work_orders_assigned_cs_user_id` (`assigned_cs_user_id`) USING BTREE,
  KEY `idx_work_orders_status` (`status`) USING BTREE,
  KEY `idx_work_orders_priority` (`priority`) USING BTREE,
  KEY `idx_work_orders_order_type` (`order_type`) USING BTREE,
  KEY `idx_work_orders_platform` (`platform`) USING BTREE,
  KEY `idx_work_orders_created_at` (`created_at`) USING BTREE,
  KEY `idx_work_orders_status_priority` (`status`,`priority`) USING BTREE,
  KEY `idx_wo_status_deleted_ctime` (`status`,`deleted`,`created_at`),
  KEY `idx_wo_status_deleted_utime` (`status`,`deleted`,`updated_at`),
  KEY `idx_work_orders_status_created` (`status`,`created_at`),
  KEY `idx_work_orders_cs_status` (`assigned_cs_user_id`,`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宸ュ崟琛?;

CREATE TABLE IF NOT EXISTS customer_warning_rule (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  rule_name VARCHAR(100) NOT NULL COMMENT '规则名称',
  monitor_stage VARCHAR(50) NOT NULL COMMENT '监控阶段: AT_RISK/CHURNED',
  trigger_condition VARCHAR(50) NOT NULL COMMENT '触发条件',
  threshold_value INT DEFAULT 0 COMMENT '条件阈值',
  action_type VARCHAR(50) NOT NULL COMMENT '处理动作',
  action_params VARCHAR(500) DEFAULT NULL COMMENT '动作参数JSON',
  enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  priority INT DEFAULT 0 COMMENT '优先级'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户生命周期预警规则表';

INSERT INTO customer_warning_rule (rule_name, monitor_stage, trigger_condition, threshold_value, action_type, action_params, enabled, priority) VALUES
('连续7天无活跃', 'AT_RISK', 'NO_ACTIVITY_DAYS', 7, 'NOTIFY_CS', '{"template":"customer_inactive_warning"}', 1, 10),
('严重流失风险', 'CHURNED', 'NO_ACTIVITY_DAYS', 14, 'SEND_COUPON', '{"couponId":1001}', 1, 5),
('收到负面评价', 'AT_RISK', 'NEGATIVE_FEEDBACK', 1, 'MARK_VIP', '{"priority":"high"}', 1, 8);
